### PR TITLE
Adding rv32e tests in riscv-test-suite

### PR DESCRIPTION
**Pull request by bilalsakhawat-10xe**
The tests generated for rv32e using riscv-ctg had some minor issues, which have been fixed in the PR [Fix rv32e tests generation](https://github.com/riscv/riscv-ctg/pull/9). Now these tests can be added to riscv-test-suite. The tests generated are tested on sail ISS (spike does not support rv32e). And existing tests are not affected, they still pass on both sail and spike. 

When this PR [Adding generation support for rv32em and rv32ec Tests](https://github.com/riscv/riscv-ctg/pull/10) will merge into the riscv-ctg then rv32ec and rv32em tests can also be added.

### CODE REVIEW

**Comment by allenjbaum** [comment]
This is great - but what I'm not seeing here is a coverage report.
I would expect that all the text pass (on either an RV32I or and RV32E -
since the difference is primarily restricting which registers are used.
However, the coverage can change, i.e. if I took the existing tests and
just deleted every instruction that used X16-31, they might pass
  - but they would also lose coverage because a walking 1s test would test
only some of the bits.
So, I'd like to see the coverage report in the PR as well.

**Comment by neelgala** [comment]
@bilalsakhawat-10xe you can generate the coverage reports and artifacts using the `--coverage` command of riscof with the SAIL plugin. 
@allenjbaum can we push these into the riscof branch instead ? If not, then bilal will need to push in the reference signatures as well.

**Comment by bilalsakhawat-10xe** [comment]
The coverage report is attached below in the form of screen shots as html file is not supported. Some of the instructions have zero coverage but their tests passed, instructions are executed and I checked the opcode, it's also correct. There might be some issue with riscv-isac.

image
image

**Comment by neelgala** [comment]
@bilalsakhawat-10xe can you post this as an issue on isac as well along with steps to replicate? Also make sure you are using the latest version of the tools.

**Comment by bilalsakhawat-10xe** [comment]
> @bilalsakhawat-10xe can you post this as an issue on isac as well along with steps to replicate? Also make sure you are using the latest version of the tools.

sure.

**Comment by neelgala** [comment]
@bilalsakhawat-10xe The latest riscv-isac has this fixed now (https://github.com/riscv/riscv-isac/pull/15)

**Comment by bilalsakhawat-10xe** [comment]
> @bilalsakhawat-10xe The latest riscv-isac has this fixed now ([riscv/riscv-isac#15](https://github.com/riscv/riscv-isac/pull/15))

**Comment by bilalsakhawat-10xe** [comment]
> > @bilalsakhawat-10xe The latest riscv-isac has this fixed now ([riscv/riscv-isac#15](https://github.com/riscv/riscv-isac/pull/15))#199 
Let me check again.

**Comment by bilalsakhawat-10xe** [comment]
The updated coverage report:
image
image

**Comment by allenjbaum** [comment]
If the coverage report isn't .html, what format is it in? Or, was it just
that it wasn't in a form that worked for email?
To answer an earlier question: if these tests are being pushed into the
existing repo, the .ref files should also be pushed..
If they're only going into the riscof branch, then not necessary

**Comment by bilalsakhawat-10xe** [comment]
@allenjbaum the coverage report is in .html but I shared the screenshots because html file cannot be attached in comment. I'll push the reference files as well to this PR.

**Comment by allenjbaum** [comment]
OK, that's fine; it really wasn't necessary to attach them to the comment
(though its nice to see the numbers), but it should be put into the repo.

**Comment by bilalsakhawat-10xe** [comment]
@allenjbaum @neelgala kindly review this PR.

**Comment by neelgala** [comment]
@allenjbaum if the "E" extension is not ratified I think the "rv32e" should be named as "rv32e_unratified" ?

**Comment by allenjbaum** [comment]
absolutely - I was going to suggest exactly that renaming.

**Review by neelgala — APPROVED** [review]

**Pull request merged**
