### PR TITLE
fix for issue #195

### LINKED ISSUE #195: riscv-arch-test/riscv-test-suite/rv64i_m/K_unratified/Makefrag
There are typos in this file. It includes .S extensions on a number of the files; the extensions should be removed

### PR DESCRIPTION
**Pull request by neelgala**
close #195

### CODE REVIEW

**Comment by liweiwei90** [comment]
@neelgala Hi, Neel,
Our PLCT lab is trying to improve the arch tests for K extension. Despite this problem, we found several problem in current tests:
1. Some tests(for example sm4ed) needs update because the instruction formats have been changed in the new spec.
2. Some reference signatures needs update because the instructions have changed to sign-extended results in the new spec.
3. The zip and unzip instructions is not supported in RV64 in the new spec.
4. The coverage for S-boxes in aes64ks1i, sm4ed and sm4ks needs improve while XLEN=64. They all only use the low 32 bits of the data. So byte_count with overlap = "N" cannot cover all the index of S-boxes.
And there is a bug when using byte_count overlap="Y" before. 
I'm trying to solve these problems. The changes for riscv_ctg and riscv_isac have been uploaded in previous PR. The changes for riscv-arch-tests is working in progress in [k-extension](https://github.com/liweiwei90/riscv-arch-test/tree/k-extension. )
However I'm trouble in generating the coverage report. I'm trying to generate the report by riscv_isac with spike as plugin one by one, like this:
`riscv_isac --verbose info coverage -d -t sm4ks.log --parser-name spike --decoder-name internaldecoder -o coverage.rpt --sig-label begin_signature end_signature --test-label rvtest_code_begin rvtest_code_end -e ./work/rv64i_m/K_unratified/sm4ks-01.elf -c ./riscv-test-stats/coverage/dataset.yaml -c ./riscv-test-stats/coverage/rv64ik.yaml -x 64 -l sm4ks`

The spike log is generated with option "--l", like this:
```
core   0: 0x0000000000001000 (0x00000297) auipc   t0, 0x0
core   0: 0x0000000000001004 (0x02028593) addi    a1, t0, 32
core   0: 0x0000000000001008 (0xf1402573) csrr    a0, mhartid
core   0: 0x000000000000100c (0x0182b283) ld      t0, 24(t0)
core   0: 0x0000000000001010 (0x00028067) jr      t0
```
The original riscv_isac cannot recognize it because of lost of ":" in the instr_pattern_spike. After I changed it, it can run successfully. However all the coverage is zero in the generated coverage.rpt

```
sm4ks:
  config:
  - check ISA:=regex(.*I.*K.*)
  - check ISA:=regex(.*I.*ZKs.*)
  - check ISA:=regex(.*I.*ZKsed.*)
  op_comb:
    rs1 != rs2  and rs1 != rd and rs2 != rd: 0
    rs1 == rd != rs2: 0
    rs1 == rs2 != rd: 0
    rs1 == rs2 == rd: 0
    rs2 == rd != rs1: 0
    coverage: 0/5
  opcode:
    sm4ks: 0
    coverage: 0/1
  rd:
    x0: 0
    x1: 0
    x10: 0
    x11: 0
    x12: 0
    x13: 0
    x14: 0
    x15: 0
    x16: 0
    x17: 0
    x18: 0
    x19: 0
    x2: 0
    x20: 0
    x21: 0
    x22: 0
    x23: 0
    x24: 0
    x25: 0
    x26: 0
    x27: 0
    x28: 0
    x29: 0
    x3: 0
    x30: 0
    x31: 0
    x4: 0
    x5: 0
    x6: 0
    x7: 0
    x8: 0
    x9: 0
    coverage: 0/32
  ...
  val_comb:
    'rs1_val == 0x0706050403020100 and rs2_val == 0x0b0a090807060504 and imm_val == 0 #nosat': 0  # Byte Count
    'rs1_val == 0xbc36b151aeb006fc and rs2_val == 0x2cab43d86576923c and imm_val == 0x3 #nosat': 0 # Uniform Random 1
    'rs1_val == 0x156fe482f9fcd292 and rs2_val == 0x24c6435c8dca0621 and imm_val == 0x0 #nosat': 0 # Uniform Random 2
    'rs1_val == 0xa757e91e027e5943 and rs2_val == 0xda73ec2605e6750f and imm_val == 0x2 #nosat': 0 # Uniform Random 3
  ...
    'rs1_val == 0x0706050403020100 and rs2_val == 0x0b0a090807060504 and imm_val == 3 #nosat': 0 # Byte Count
    'rs1_val == 0x0706050403020100 and rs2_val == 0x0b0a090807060504 and imm_val == 2 #nosat': 0 # Byte Count
    'rs1_val == 0x0706050403020100 and rs2_val == 0x0b0a090807060504 and imm_val == 1 #nosat': 0 # Byte Count
    coverage: 0/276
  total_coverage: 0/378
```

Is there any error in my steps? I found there is no support for K extension in the internaldecoder.py. Does it matter?
Additionally, Is there any way to generate the whole coverages for all instructions? 
Thanks a lot.
Li Weiwei

**Comment by allenjbaum** [comment]
I'd like to split off original filename issue from the need to regenerate tests to match the updated specs and close issue#195 with this pr#198.
Could you please copy this into a separate issue to update the tests to match the latest tests? This includes
 - format changes
 - sign extension changes
 - removing zip and unzip tests from RV64 tests only (they stay in RV32)
 
The coverage issue is separate from both of these, and, if there is a problem, should be yet a separate issue.

**Comment by liweiwei90** [comment]
OK

**Comment by neelgala** [comment]
@liweiwei90 Are the above concerns addressed in your PR: https://github.com/riscv/riscv-arch-test/pull/201 ?

**Comment by liweiwei90** [comment]
> @liweiwei90 Are the above concerns addressed in your PR: #201 ?

@neelgala Yes, I have addressed these.  I used the wrong command to generate the log and support for K extension in the internaldecoder.py has been updated in https://github.com/riscv/riscv-isac/pull/18 . Thanks a lot.

**Review by MarcKarasek — APPROVED** [review]

**Pull request merged**
